<a href="https://colab.research.google.com/github/proap900/AI_LAB/blob/main/knn_algo_ai_lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# knn algorithm for 3 featured factor
import numpy as np
import math
# DATASET
age = [22, 28, 35, 41, 30, 24, 46, 39, 21, 33,
       48, 29, 37, 50, 26, 32, 43, 25, 36, 44,
       27, 31, 47, 34, 23, 38, 42, 20, 45, 40]

income = [35500, 52100, 74200, 85600, 45000, 31800, 95200, 60000, 28300, 58400,
          112600, 49500, 71300, 120000, 41700, 59900, 89100, 38000, 68500, 93400,
          42600, 55800, 108900, 63200, 30600, 70000, 87700, 25400, 96300, 76100]

type_ = ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'B',
         'C', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'B', 'B',
         'A', 'B', 'B', 'B', 'A', 'B', 'C', 'A', 'C', 'B']
class knn_class_algorithm:
    def creating_dictionary(self, age,income,type_):
        data={}
        for idx in range(30):
         data[idx]={'age':age[idx],'income':income[idx],'type_':type_[idx]}
        return data


    def print_data_in_table(self,data):
        counterA=0
        counterB=0
        counterC=0
        print("SN\t\tAge\t\tIncome\t\tType")
        for key in data:
         print(f"{key}\t\t{data[key]['age']}\t\t{data[key]['income']}\t\t{data[key]['type_']}")
         if data[key]['type_']=='A':
          counterA+=1
         elif data[key]['type_']=='B':
          counterB+=1
         else:
          counterC+=1
        print(f"A:{counterA}, B:{counterB}, C:{counterC}")

    def print_data_with_distances_using_provided_data(self,data,given_age,given_income):
        distances={}
        for key in data:
         age_diff=given_age-data[key]['age']
         print(data[key]['age'],given_age)

         income_diff=given_income-data[key]['income']
         distance = math.sqrt((age_diff ** 2) + (income_diff ** 2))
         distances[key]={'distance':distance}
         print(distances[key])
        print("SN\t\tAge\t\tIncome\t\tType\t\tdistances")
        for key in data:
         print(f"{key}\t\t{data[key]['age']}\t\t{data[key]['income']}\t\t{data[key]['type_']}\t\t{distances[key]['distance']}")
        return distances

    def return_sorted_distances_data(self,distances):
        sorted_distances = dict(sorted(distances.items(), key=lambda x: x[1]['distance']))
        print(sorted_distances)
        return sorted_distances

    def count_type_according_to_knn(self,data,sorted_distances,countmax):
        counterA=0
        counterB=0
        counterC=0
        count=0
        for key in sorted_distances:
            if data[key]['type_'] == 'A':
                print('a',key)
                counterA+=1
            if data[key]['type_'] == 'B':
                print('b',key)
                counterB+=1
            if data[key]['type_'] == 'C':
                counterC+=1
            else:
                print('wrong')

            count+=1
            if count == countmax:
                break
        return counterA,counterB,counterC

    def knn_result(self,counterA,counterB,counterC):
        print(f"A:{counterA}, B:{counterB}, C:{counterC}")
        output=max(counterA,counterB,counterC)
        print(output)
        if output==counterA:
            type_selected='A'
        elif output==counterB:
            type_selected='B'
        else:
            type_selected='C'
        # print(f"According to knn age:{given_age},income:{given_income} person have a type:{type_selected}")
        return type_selected

    def knn_algorithm(self, age, income, type_, given_age, given_income, countmax):
        dictionary=self.creating_dictionary(age,income,type_)
        self.print_data_in_table(dictionary)
        distances_dictionary=self.print_data_with_distances_using_provided_data(dictionary,given_age,given_income)
        sorted_distances_dictionary=self.return_sorted_distances_data(distances_dictionary)
        A,B,C=self.count_type_according_to_knn(dictionary,sorted_distances_dictionary,countmax)
        result=self.knn_result(A,B,C)
        return result


given_age=int(input("Enter age :"))
given_income=int(input("Enter income:"))
# given_age=30
# given_income=60000

countmax=5
knn=knn_class_algorithm()
result =knn.knn_algorithm(age,income,type_,given_age,given_income,countmax)
print(f"According to knn age:{given_age},income:{given_income} person  may  wear type:{result} pants")

Enter age :32
Enter income:60000
SN		Age		Income		Type
0		22		35500		A
1		28		52100		B
2		35		74200		A
3		41		85600		C
4		30		45000		B
5		24		31800		A
6		46		95200		C
7		39		60000		B
8		21		28300		A
9		33		58400		B
10		48		112600		C
11		29		49500		A
12		37		71300		B
13		50		120000		A
14		26		41700		A
15		32		59900		B
16		43		89100		C
17		25		38000		A
18		36		68500		B
19		44		93400		B
20		27		42600		A
21		31		55800		B
22		47		108900		B
23		34		63200		B
24		23		30600		A
25		38		70000		B
26		42		87700		C
27		20		25400		A
28		45		96300		C
29		40		76100		B
A:11, B:13, C:6
22 32
{'distance': 24500.00204081624}
28 32
{'distance': 7900.001012658163}
35 32
{'distance': 14200.000316901405}
41 32
{'distance': 25600.0015820312}
30 32
{'distance': 15000.000133333333}
24 32
{'distance': 28200.00113475175}
46 32
{'distance': 35200.0027840908}
39 32
{'distance': 7.0}
21 32
{'distance': 31700.001908517293}
33 32
{'distance': 1600.0003124999696}
48 32
{'distance': 52600.00243346002}
29 32
{'distance': 10500.00042857142}
37 32
{'distance': 11300.001106194635}
50 32
{'distance': 60000.00269999994}
26 32
{'distance': 18300.00098360653}
32 32
{'distance': 100.0}
43 32
{'distance': 29100.002079037728}
25 32
{'distance': 22000.001113636336}
36 32
{'distance': 8500.000941176419}
44 32
{'distance': 33400.002155688555}
27 32
{'distance': 17400.00071839079}
31 32
{'distance': 4200.000119047618}
47 32
{'distance': 48900.00230061344}
34 32
{'distance': 3200.000624999939}
23 32
{'distance': 29400.001377550987}
38 32
{'distance': 10000.001799999838}
42 32
{'distance': 27700.001805054093}
20 32
{'distance': 34600.002080924794}
45 32
{'distance': 36300.00232782362}
40 32
{'distance': 16100.001987577518}
SN		Age		Income		Type		distances
0		22		35500		A		24500.00204081624
1		28		52100		B		7900.001012658163
2		35		74200		A		14200.000316901405
3		41		85600		C		25600.0015820312
4		30		45000		B		15000.000133333333
5		24		31800		A		28200.00113475175
6		46		95200		C		35200.0027840908
7		39		60000		B		7.0
8		21		28300		A		31700.001908517293
9		33		58400		B		1600.0003124999696
10		48		112600		C		52600.00243346002
11		29		49500		A		10500.00042857142
12		37		71300		B		11300.001106194635
13		50		120000		A		60000.00269999994
14		26		41700		A		18300.00098360653
15		32		59900		B		100.0
16		43		89100		C		29100.002079037728
17		25		38000		A		22000.001113636336
18		36		68500		B		8500.000941176419
19		44		93400		B		33400.002155688555
20		27		42600		A		17400.00071839079
21		31		55800		B		4200.000119047618
22		47		108900		B		48900.00230061344
23		34		63200		B		3200.000624999939
24		23		30600		A		29400.001377550987
25		38		70000		B		10000.001799999838
26		42		87700		C		27700.001805054093
27		20		25400		A		34600.002080924794
28		45		96300		C		36300.00232782362
29		40		76100		B		16100.001987577518
{7: {'distance': 7.0}, 15: {'distance': 100.0}, 9: {'distance': 1600.0003124999696}, 23: {'distance': 3200.000624999939}, 21: {'distance': 4200.000119047618}, 1: {'distance': 7900.001012658163}, 18: {'distance': 8500.000941176419}, 25: {'distance': 10000.001799999838}, 11: {'distance': 10500.00042857142}, 12: {'distance': 11300.001106194635}, 2: {'distance': 14200.000316901405}, 4: {'distance': 15000.000133333333}, 29: {'distance': 16100.001987577518}, 20: {'distance': 17400.00071839079}, 14: {'distance': 18300.00098360653}, 17: {'distance': 22000.001113636336}, 0: {'distance': 24500.00204081624}, 3: {'distance': 25600.0015820312}, 26: {'distance': 27700.001805054093}, 5: {'distance': 28200.00113475175}, 16: {'distance': 29100.002079037728}, 24: {'distance': 29400.001377550987}, 8: {'distance': 31700.001908517293}, 19: {'distance': 33400.002155688555}, 27: {'distance': 34600.002080924794}, 6: {'distance': 35200.0027840908}, 28: {'distance': 36300.00232782362}, 22: {'distance': 48900.00230061344}, 10: {'distance': 52600.00243346002}, 13: {'distance': 60000.00269999994}}
b 7
wrong
b 15
wrong
b 9
wrong
b 23
wrong
b 21
wrong
A:0, B:5, C:0
5
According to knn age:32,income:60000 person  may  wear type:B pants

In [4]:
# knn algorithm n featured
import math

class knn_class_algorithm:
    def creating_dictionary(self, age, income, education, experience, type_):
        data = {}
        for idx in range(len(age)):
            data[idx] = {
                'age': age[idx],
                'income': income[idx],
                'education': education[idx],
                'experience': experience[idx],
                'type_': type_[idx]
            }
        return data

    def print_data_in_table(self, data):
        counterA = 0
        counterB = 0
        counterC = 0
        print("SN\tAge\tIncome\tEducation\tExperience\tType")
        for key in data:
            print(f"{key}\t{data[key]['age']}\t{data[key]['income']}\t{data[key]['education']}\t\t{data[key]['experience']}\t\t{data[key]['type_']}")
            if data[key]['type_'] == 'A':
                counterA += 1
            elif data[key]['type_'] == 'B':
                counterB += 1
            else:
                counterC += 1
        print(f"Count -> A:{counterA}, B:{counterB}, C:{counterC}")

    def print_data_with_distances_using_provided_data(self, data, given_features):
        distances = {}
        for key in data:
            dist_sum = 0
            for feature in ['age', 'income', 'education', 'experience']:
                diff = given_features[feature] - data[key][feature]
                dist_sum += diff ** 2
            distance = math.sqrt(dist_sum)
            print(distance)
            distances[key] = {'distance': distance}
        print("SN\tAge\tIncome\tEducation\tExperience\tType\tDistance")
        for key in data:
            print(f"{key}\t{data[key]['age']}\t{data[key]['income']}\t{data[key]['education']}\t\t{data[key]['experience']}\t\t{data[key]['type_']}\t{distances[key]['distance']:.2f}")
        return distances

    def return_sorted_distances_data(self, distances):
        sorted_distances = dict(sorted(distances.items(), key=lambda x: x[1]['distance']))
        return sorted_distances

    def count_type_according_to_knn(self, data, sorted_distances, countmax):
        counterA = 0
        counterB = 0
        counterC = 0
        count = 0
        for key in sorted_distances:
            if data[key]['type_'] == 'A':
                counterA += 1
            elif data[key]['type_'] == 'B':
                counterB += 1
            elif data[key]['type_'] == 'C':
                counterC += 1
            count += 1
            if count == countmax:
                break
        return counterA, counterB, counterC

    def knn_result(self, counterA, counterB, counterC):
        print(f"Counts -> A:{counterA}, B:{counterB}, C:{counterC}")
        output = max(counterA, counterB, counterC)
        if output == counterA:
            type_selected = 'A'
        elif output == counterB:
            type_selected = 'B'
        else:
            type_selected = 'C'
        return type_selected

    def knn_algorithm(self, age, income, education, experience, type_, given_features, countmax):
        dictionary = self.creating_dictionary(age, income, education, experience, type_)
        self.print_data_in_table(dictionary)
        distances_dictionary = self.print_data_with_distances_using_provided_data(dictionary, given_features)
        sorted_distances_dictionary = self.return_sorted_distances_data(distances_dictionary)
        A, B, C = self.count_type_according_to_knn(dictionary, sorted_distances_dictionary, countmax)
        result = self.knn_result(A, B, C)
        return result


# Your original data
age = [22, 28, 35, 41, 30, 24, 46, 39, 21, 33,
       48, 29, 37, 50, 26, 32, 43, 25, 36, 44,
       27, 31, 47, 34, 23, 38, 42, 20, 45, 40]

income = [35500, 52100, 74200, 85600, 45000, 31800, 95200, 60000, 28300, 58400,
          112600, 49500, 71300, 120000, 41700, 59900, 89100, 38000, 68500, 93400,
          42600, 55800, 108900, 63200, 30600, 70000, 87700, 25400, 96300, 76100]

type_ = ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'B',
         'C', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'B', 'B',
         'A', 'B', 'B', 'B', 'A', 'B', 'C', 'A', 'C', 'B']

# New features you want to add (education in years, experience in years)
education = [12, 16, 14, 18, 13, 12, 20, 16, 10, 15,
             20, 14, 16, 22, 11, 15, 19, 13, 17, 21,
             12, 16, 20, 15, 10, 18, 19, 9, 21, 17]

experience = [1, 5, 10, 15, 3, 2, 20, 12, 0, 7,
              21, 6, 8, 23, 3, 9, 15, 4, 10, 17,
              2, 7, 20, 10, 1, 12, 15, 0, 18, 11]

# Query point (new person)
given_features = {
    'age': 30,
    'income': 60000,
    'education': 16,
    'experience': 5
}

countmax = 5

knn = knn_class_algorithm()
result = knn.knn_algorithm(age, income, education, experience, type_, given_features, countmax)

print(f"\nAccording to KNN, person with features {given_features} is classified as type: {result}")

SN	Age	Income	Education	Experience	Type
0	22	35500	12		1		A
1	28	52100	16		5		B
2	35	74200	14		10		A
3	41	85600	18		15		C
4	30	45000	13		3		B
5	24	31800	12		2		A
6	46	95200	20		20		C
7	39	60000	16		12		B
8	21	28300	10		0		A
9	33	58400	15		7		B
10	48	112600	20		21		C
11	29	49500	14		6		A
12	37	71300	16		8		B
13	50	120000	22		23		A
14	26	41700	11		3		A
15	32	59900	15		9		B
16	43	89100	19		15		C
17	25	38000	13		4		A
18	36	68500	17		10		B
19	44	93400	21		17		B
20	27	42600	12		2		A
21	31	55800	16		7		B
22	47	108900	20		20		B
23	34	63200	15		10		B
24	23	30600	10		1		A
25	38	70000	18		12		B
26	42	87700	19		15		C
27	20	25400	9		0		A
28	45	96300	21		18		C
29	40	76100	17		11		B
Count -> A:11, B:13, C:6
24500.001959183595
7900.000253164553
14200.001901408323
25600.00439453087
15000.000433333327
28200.00108156026
35200.00705965838
11.40175425099138
31700.002239747555
1600.0043749940185
52600.00566539894
10500.000285714283
11300.00256637139
60000.006333332996
18300.001229508154
100.1049449328054
29100.00477663191
22000.000795454533
8500.003647058042
33400.00546407141
17400.000977011467
4200.000595238053
48900.0054192226
3200.006562493271
29400.001717687024
10000.00584999829
27700.00456678663
34600.002514450774
36300.0057713494
16100.004254657822
SN	Age	Income	Education	Experience	Type	Distance
0	22	35500	12		1		A	24500.00
1	28	52100	16		5		B	7900.00
2	35	74200	14		10		A	14200.00
3	41	85600	18		15		C	25600.00
4	30	45000	13		3		B	15000.00
5	24	31800	12		2		A	28200.00
6	46	95200	20		20		C	35200.01
7	39	60000	16		12		B	11.40
8	21	28300	10		0		A	31700.00
9	33	58400	15		7		B	1600.00
10	48	112600	20		21		C	52600.01
11	29	49500	14		6		A	10500.00
12	37	71300	16		8		B	11300.00
13	50	120000	22		23		A	60000.01
14	26	41700	11		3		A	18300.00
15	32	59900	15		9		B	100.10
16	43	89100	19		15		C	29100.00
17	25	38000	13		4		A	22000.00
18	36	68500	17		10		B	8500.00
19	44	93400	21		17		B	33400.01
20	27	42600	12		2		A	17400.00
21	31	55800	16		7		B	4200.00
22	47	108900	20		20		B	48900.01
23	34	63200	15		10		B	3200.01
24	23	30600	10		1		A	29400.00
25	38	70000	18		12		B	10000.01
26	42	87700	19		15		C	27700.00
27	20	25400	9		0		A	34600.00
28	45	96300	21		18		C	36300.01
29	40	76100	17		11		B	16100.00
Counts -> A:0, B:5, C:0

According to KNN, person with features {'age': 30, 'income': 60000, 'education': 16, 'experience': 5} is classified as type: B

In [5]:
# knn alogrithm 4 categorical data
import numpy as np
from collections import Counter

# Sample dataset with 4 numeric + 4 categorical features

age = [22, 28, 35, 41, 30, 24, 46, 39, 21, 33,
       48, 29, 37, 50, 26, 32, 43, 25, 36, 44,
       27, 31, 47, 34, 23, 38, 42, 20, 45, 40]

income = [35500, 52100, 74200, 85600, 45000, 31800, 95200, 60000, 28300, 58400,
          112600, 49500, 71300, 120000, 41700, 59900, 89100, 38000, 68500, 93400,
          42600, 55800, 108900, 63200, 30600, 70000, 87700, 25400, 96300, 76100]

education = [12, 16, 14, 18, 13, 12, 20, 16, 10, 15,
             20, 14, 16, 22, 11, 15, 19, 13, 17, 21,
             12, 16, 20, 15, 10, 18, 19, 9, 21, 17]

experience = [1, 5, 10, 15, 3, 2, 20, 12, 0, 7,
              21, 6, 8, 23, 3, 9, 15, 4, 10, 17,
              2, 7, 20, 10, 1, 12, 15, 0, 18, 11]

# Categorical features (4 of them)
gender = ['M', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F',
          'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M',
          'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F', 'M', 'F']

city = ['NY', 'LA', 'NY', 'CHI', 'LA', 'CHI', 'NY', 'LA', 'CHI', 'NY',
        'LA', 'CHI', 'NY', 'LA', 'CHI', 'NY', 'LA', 'CHI', 'NY', 'LA',
        'CHI', 'NY', 'LA', 'CHI', 'NY', 'LA', 'CHI', 'NY', 'LA', 'CHI']

profession = ['Engineer', 'Doctor', 'Artist', 'Engineer', 'Artist', 'Doctor', 'Engineer', 'Doctor', 'Artist', 'Engineer',
              'Artist', 'Doctor', 'Engineer', 'Artist', 'Doctor', 'Engineer', 'Artist', 'Doctor', 'Engineer', 'Artist',
              'Doctor', 'Engineer', 'Artist', 'Doctor', 'Engineer', 'Artist', 'Doctor', 'Engineer', 'Artist', 'Doctor']

marital_status = ['Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married',
                  'Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married',
                  'Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married', 'Single', 'Married']

type_ = ['A', 'B', 'A', 'C', 'B', 'A', 'C', 'B', 'A', 'B',
         'C', 'A', 'B', 'A', 'A', 'B', 'C', 'A', 'B', 'B',
         'A', 'B', 'B', 'B', 'A', 'B', 'C', 'A', 'C', 'B']

# Normalize numeric features
def normalize(features):
    features = np.array(features)
    min_val = features.min()
    max_val = features.max()
    return (features - min_val) / (max_val - min_val)

age_norm = normalize(age)
income_norm = normalize(income)
education_norm = normalize(education)
experience_norm = normalize(experience)

# Combine numeric features as a list of lists
numeric_features = list(zip(age_norm, income_norm, education_norm, experience_norm))

# Categorical features combined
categorical_features = list(zip(gender, city, profession, marital_status))

def mixed_distance(point1_num, point2_num, point1_cat, point2_cat, weight_num=0.7, weight_cat=0.3):
    # Euclidean distance for numeric features
    num_dist = np.linalg.norm(np.array(point1_num) - np.array(point2_num))
    # Hamming distance for categorical features (sum of mismatches)
    cat_dist = sum(p1 != p2 for p1, p2 in zip(point1_cat, point2_cat)) / len(point1_cat)
    # Weighted sum
    return weight_num * num_dist + weight_cat * cat_dist

def knn_mixed(features_num, features_cat, labels, query_num, query_cat, k=5):
    distances = []
    for i in range(len(labels)):
        dist = mixed_distance(features_num[i], features_num[i], features_cat[i], features_cat[i], weight_num=0.7, weight_cat=0.3)
        dist = mixed_distance(features_num[i], query_num, features_cat[i], query_cat)
        distances.append((dist, labels[i]))
    distances.sort(key=lambda x: x[0])
    neighbors = distances[:k]
    votes = Counter(label for _, label in neighbors)
    return votes.most_common(1)[0][0]

# Example query
query_numeric = [30, 60000, 16, 5]
query_numeric_norm = [
    (30 - min(age)) / (max(age) - min(age)),
    (60000 - min(income)) / (max(income) - min(income)),
    (16 - min(education)) / (max(education) - min(education)),
    (5 - min(experience)) / (max(experience) - min(experience))
]

query_categorical = ('M', 'NY', 'Engineer', 'Single')

result = knn_mixed(numeric_features, categorical_features, type_, query_numeric_norm, query_categorical, k=5)
print(f"Predicted type for query: {result}")

Predicted type for query: B